# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Package Publisher

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: "Build & Publish Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout"
      - uses: actions/setup-node@v3
        name: "Setup Node"
        with:
          node-version: 18
      - run: npm i
        name: "Install Dependencies"
      - run: npm run build
        name: "Build Package"
      - uses: JS-DevTools/npm-publish@v1
        name: "Publish to NPM Registry"
        with:
          token: ${{ secrets.NODE_API_TOKEN }}
          registry: https://registry.npmjs.org/
          greater-version-only: true
      - uses: jossef/action-set-json-field@v2
        name: "Change Package Name for GitHub"
        with:
          file: package.json
          field: name
          value: "@${{ github.repository_owner }}/${{ github.event.repository.name }}"
      - uses: JS-DevTools/npm-publish@v1
        name: "Publish to GitHub Packages Registry"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
          check-version: true
          greater-version-only: true
